version: "3.9"

services:
  api:
    build: .
    container_name: ravenhall_api
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    image: postgres:16-alpine
    container_name: ravenhall_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ravenhall_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: ravenhall_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
